baseURL: "https://zhouwangqian.github.io/" 
title: Wangqian Zhou
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: More about me
          url: moreaboutme/
          weight: 1
        - name: Keywords
          url: tags/
          weight: 2
        - name: Journal papers
          url: papers/
          weight: 3
        - name: Presentations
          url: pres/
          weight: 4
        - name: Archive
          url: archive/
          weight: 5
        - name: Happenings
          url: happenings/
          weight: 6
        - name: Search  
          url: search/  
          weight: 7


params:
    description: "This website hosts Wangqian Zhou's curriculum vitae, research papers, and contact information."
    author: Wangqian Zhou
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["pres","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Wangqian Zhou
          subtitle: "<span style='font-size: 1.1em; color: grey;'>(<em>Chinese</em>: 周望千; <em>pinyin</em>: Zhou Wangqian; <em>IPA Mandarin</em>: /ʈʂoʊ55 wɑŋ51 tɕʰjɛn55/)</span> <p style='margin-top: 0.5em;'> 

¡Hola! Soy Wangqian. I'm a 2nd-year PhD student in Linguistics at the Chinese University of Hong Kong, under the joint supervision of <a href='https://ling.cuhk.edu.hk/people/peggy/' style='color: #893f8c;'>**Prof. Peggy Mok 莫碧琪**</a> (CUHK)
and <a href='http://paslab.phonetics.org.cn/?p=581' style='color: #893f8c;'>**Prof. Aijun Li 李愛軍**</a> (Chinese Academy of Social Sciences). <p style='margin-top: 0.5em;'> 

As a phonetician, I'm drawn to the **<a style='color: #893f8c;'>Do-Re-Mis</a>** and **<a style='color: #893f8c;'>Rat-A-Tats</a>** of speech (esp., production, perception, and acquisition of tone and intonation; affective and attitudinal prosody; prosodic iconicity; and the relationship between musicality and speech abilities). <p style='margin-top: 0.5em;'> 

I'm currently working on the **<a style='color: #893f8c;'>production and perception of tones in relation to different levels of prominence in Changsha Xiang and Plastic Mandarin</a>**, aiming to understand how phonetic correlates (esp., phonatory properties) are encoded and perceptually weighted. In addition, I'm also involved in Prof. Li's project on intonational typology, where I focus on **<a style='color: #893f8c;'>the intonation of Changsha Xiang</a>**.<p style='margin-top: 0.5em;'>"
          imageUrl: "profile_picture.JPG"
          imageWidth: 220
          imageHeight: 220
          buttons:
            - name: More about me
              url: moreaboutme/
            - name: Keywords
              url: tags/
            - name: Journal papers
              url: papers/
            - name: Presentations
              url: pres/
            - name: Archive
              url: archive/
            - name: Happenings
              url: happenings/
            - name: Search  
              url: search/  

    socialIcons:
        - name: CV
          url: zhoucv.pdf
        - name: ORCID
          url: https://orcid.org/0009-0007-0892-0513
        - name: OSF
          url: https://osf.io/tazds
        - name: GitHub
          url: https://github.com/ZhouWangqian
        - name: Facebook
          url: https://www.facebook.com/zhou.wang.qian
        - name: Email
          url: mailto:zhouwangqian@link.cuhk.edu.hk
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Wangqian‘s Homepage"
      icon: favicon.ico
      iconHeight: 23

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
     home:
         - HTML
         - RSS
         - JSON
